name: petshop-prod

services:
  petshop:
    image: petshop:1.0.0-LTS
    container_name: petshop
    environment:
      - DB_URL=jdbc:postgresql://localhost:5432/petshop
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - ALLOWED_ORIGIN=*
      - JWT_KEY=SuaChaveSecretaMuitoSeguraParaJWT
      - UPLOAD_DIR=~/Documentos/petshop/uploads
    restart: always
    network_mode: host

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    network_mode: host

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    network_mode: host
