global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "petshop-api"
    static_configs:
      - targets: ["localhost:8181"]
    metrics_path: "/actuator/prometheus"
